# Generated by Django 3.1.7 on 2021-03-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guests_number', models.SmallIntegerField()),
                ('room_type', models.SmallIntegerField(choices=[(1, 'Individual'), (2, 'Doble'), (3, 'Triple'), (4, 'Cuadruple')])),
                ('total_price', models.FloatField()),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('unique_code', models.CharField(default='', max_length=16, unique=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.contact')),
            ],
        ),
    ]
